In [1]:
import pandas as pd
import numpy as np

# World cup match results

In [2]:
men_worldcup_results = pd.read_csv('WorldCupMatches.csv')
women_worldcup_results = pd.read_csv('WomenWorldCupMatches.csv')

## Men dataset cleanup

In [3]:
men_worldcup_results = men_worldcup_results.iloc[:852]

men_worldcup_results.insert(2, 'Gender', 'M')

men_worldcup_results.head()

,Year,Datetime,Gender,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,...,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
0,1930.0,13 Jul 1930 - 15:00,M,Group 1,Pocitos,Montevideo,France,4.0,1.0,Mexico,...,4444.0,3.0,0.0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201.0,1096.0,FRA,MEX
1,1930.0,13 Jul 1930 - 15:00,M,Group 4,Parque Central,Montevideo,USA,3.0,0.0,Belgium,...,18346.0,2.0,0.0,MACIAS Jose (ARG),MATEUCCI Francisco (URU),WARNKEN Alberto (CHI),201.0,1090.0,USA,BEL
2,1930.0,14 Jul 1930 - 12:45,M,Group 2,Parque Central,Montevideo,Yugoslavia,2.0,1.0,Brazil,...,24059.0,2.0,0.0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201.0,1093.0,YUG,BRA
3,1930.0,14 Jul 1930 - 14:50,M,Group 3,Pocitos,Montevideo,Romania,3.0,1.0,Peru,...,2549.0,1.0,0.0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201.0,1098.0,ROU,PER
4,1930.0,15 Jul 1930 - 16:00,M,Group 1,Parque Central,Montevideo,Argentina,1.0,0.0,France,...,23409.0,0.0,0.0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201.0,1085.0,ARG,FRA

In [4]:
argentina = men_worldcup_results[(men_worldcup_results['Home Team Name'] =='Argentina') | (men_worldcup_results['Away Team Name'] =='Argentina' )]
argentina

,Year,Datetime,Gender,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,...,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
4,1930.0,15 Jul 1930 - 16:00,M,Group 1,Parque Central,Montevideo,Argentina,1.0,0.0,France,...,23409.0,0.0,0.0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201.0,1085.0,ARG,FRA
10,1930.0,19 Jul 1930 - 15:00,M,Group 1,Estadio Centenario,Montevideo,Argentina,6.0,3.0,Mexico,...,42100.0,3.0,1.0,SAUCEDO Ulises (BOL),ALONSO Gualberto (URU),RADULESCU Constantin (ROU),201.0,1086.0,ARG,MEX
14,1930.0,22 Jul 1930 - 14:45,M,Group 1,Estadio Centenario,Montevideo,Argentina,3.0,1.0,Chile,...,41459.0,2.0,1.0,LANGENUS Jean (BEL),CRISTOPHE Henry (BEL),SAUCEDO Ulises (BOL),201.0,1084.0,ARG,CHI
15,1930.0,26 Jul 1930 - 14:45,M,Semi-finals,Estadio Centenario,Montevideo,Argentina,6.0,1.0,USA,...,72886.0,1.0,0.0,LANGENUS Jean (BEL),VALLEJO Gaspar (MEX),WARNKEN Alberto (CHI),202.0,1088.0,ARG,USA
17,1930.0,30 Jul 1930 - 14:15,M,Final,Estadio Centenario,Montevideo,Uruguay,4.0,2.0,Argentina,...,68346.0,1.0,2.0,LANGENUS Jean (BEL),SAUCEDO Ulises (BOL),CRISTOPHE Henry (BEL),405.0,1087.0,URU,ARG
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
834,2014.0,01 Jul 2014 - 13:00,M,Round of 16,Arena de Sao Paulo,Sao Paulo,Argentina,1.0,0.0,Switzerland,...,63255.0,0.0,0.0,ERIKSSON Jonas (SWE),KLASENIUS Mathias (SWE),WARNMARK Daniel (SWE),255951.0,300186503.0,ARG,SUI
842,2014.0,01 Jul 2014 - 13:00,M,Round of 16,Arena de Sao Paulo,Sao Paulo,Argentina,1.0,0.0,Switzerland,...,63255.0,0.0,0.0,ERIKSSON Jonas (SWE),KLASENIUS Mathias (SWE),WARNMARK Daniel (SWE),255951.0,300186503.0,ARG,SUI
846,2014.0,05 Jul 2014 - 13:00,M,Quarter-finals,Estadio Nacional,Brasilia,Argentina,1.0,0.0,Belgium,...,68551.0,1.0,0.0,Nicola RIZZOLI (ITA),Renato FAVERANI (ITA),Andrea STEFANI (ITA),255953.0,300186504.0,ARG,BEL
849,2014.0,09 Jul 2014 - 17:00,M,Semi-finals,Arena de Sao Paulo,Sao Paulo,Netherlands,0.0,0.0,Argentina,...,63267.0,0.0,0.0,Cï¿½neyt ï¿½AKIR (TUR),DURAN Bahattin (TUR),ONGUN Tarik (TUR),255955.0,300186490.0,NED,ARG
851,2014.0,13 Jul 2014 - 16:00,M,Final,Estadio do Maracana,Rio De Janeiro,Germany,1.0,0.0,Argentina,...,74738.0,0.0,0.0,Nicola RIZZOLI (ITA),Renato FAVERANI (ITA),Andrea STEFANI (ITA),255959.0,300186501.0,GER,ARG

## Woman dataset cleanup

Change stage names:

In [5]:
women_worldcup_results = women_worldcup_results.replace(np.nan, '', regex=True)
women_worldcup_results['Stage'] = women_worldcup_results['Stage'].apply(lambda x: 'Group A' if (x == 'group-a') else x )
women_worldcup_results['Stage'] = women_worldcup_results['Stage'].apply(lambda x: 'Group B' if (x == 'group-b') else x )
women_worldcup_results['Stage'] = women_worldcup_results['Stage'].apply(lambda x: 'Group C' if (x == 'group-c') else x )
women_worldcup_results['Stage'] = women_worldcup_results['Stage'].apply(lambda x: 'Group D' if (x == 'group-d') else x )
women_worldcup_results['Stage'] = women_worldcup_results['Stage'].apply(lambda x: 'Group E' if (x == 'group-e') else x )
women_worldcup_results['Stage'] = women_worldcup_results['Stage'].apply(lambda x: 'Group F' if (x == 'group-f') else x )
women_worldcup_results['Stage'] = women_worldcup_results['Stage'].apply(lambda x: 'Final' if (x == 'final') else x )
women_worldcup_results['Stage'] = women_worldcup_results['Stage'].apply(lambda x: 'Quarter-finals' if (x == 'quarter-finals') else x )
women_worldcup_results['Stage'] = women_worldcup_results['Stage'].apply(lambda x: 'Semi-finals' if (x == 'semi-finals') else x )
women_worldcup_results['Stage'] = women_worldcup_results['Stage'].apply(lambda x: 'Third place' if (x == 'third-place') else x )
women_worldcup_results['Stage'] = women_worldcup_results['Stage'].apply(lambda x: 'Round of 16' if (x == 'round-16') else x )

Separate score to each side:

In [6]:
women_worldcup_results['Score'] = women_worldcup_results['Score'].apply(lambda x: x.replace('-','â€“'))

women_worldcup_results['Home Team Goals'] = women_worldcup_results['Score'].apply(lambda x: x.split('â€“')[0])
women_worldcup_results['Away Team Goals'] = women_worldcup_results['Score'].apply(lambda x: x.split('â€“')[1])

In [7]:
women_worldcup_results = women_worldcup_results[['Year','Stage','Home Team Name','Home Team Goals','Away Team Goals','Away Team Name','Win conditions']]
women_worldcup_results.insert(1, 'Gender', 'F')

In [8]:
women_worldcup_results

,Year,Gender,Stage,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions
0,1991,F,Group A,China PR,4,0,Norway,
1,1991,F,Group A,Denmark,3,0,New Zealand,
2,1991,F,Group A,Norway,4,0,New Zealand,
3,1991,F,Group A,China PR,2,2,Denmark,
4,1991,F,Group A,China PR,4,1,New Zealand,
...,...,...,...,...,...,...,...,...
279,2019,F,Quarter-finals,Germany,1,2,Sweden,
280,2019,F,Semi-finals,England,1,2,United States,
281,2019,F,Semi-finals,Netherlands,1,0,Sweden,
282,2019,F,Third place,England,1,2,Sweden,
283,2019,F,Final,United States,2,0,Netherlands,

In [9]:
argentina = women_worldcup_results[(women_worldcup_results['Home Team Name'] =='Argentina') | (women_worldcup_results['Away Team Name'] =='Argentina' )]
argentina.head(15)

,Year,Gender,Stage,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,Win conditions
97,2003,F,Group C,Japan,6,0,Argentina,
99,2003,F,Group C,Canada,3,0,Argentina,
101,2003,F,Group C,Argentina,1,6,Germany,
116,2007,F,Group A,Germany,11,0,Argentina,
118,2007,F,Group A,Argentina,0,1,Japan,
121,2007,F,Group A,England,6,1,Argentina,
251,2019,F,Group D,Argentina,0,0,Japan,
253,2019,F,Group D,England,1,0,Argentina,
255,2019,F,Group D,Scotland,3,3,Argentina,

## Append both datasets

In [10]:
world_cup_results = men_worldcup_results.append(women_worldcup_results)

Clean nan and turn year to int:

In [11]:
world_cup_results = world_cup_results.replace(np.nan, '', regex=True)

world_cup_results['Year'] = world_cup_results['Year'].apply(lambda x: int(x))

Clean different country names:

In [12]:
world_cup_results['Home Team Name'] = world_cup_results['Home Team Name'].apply(lambda x : 'Germany' if (x == 'German DR' or x == 'Germany FR') else x )
world_cup_results['Home Team Name'] = world_cup_results['Home Team Name'].apply(lambda x : 'Iran' if (x == 'IR Iran') else x )
world_cup_results

,Year,Datetime,Gender,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,...,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
0,1930,13 Jul 1930 - 15:00,M,Group 1,Pocitos,Montevideo,France,4,1,Mexico,...,4444,3,0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201,1096,FRA,MEX
1,1930,13 Jul 1930 - 15:00,M,Group 4,Parque Central,Montevideo,USA,3,0,Belgium,...,18346,2,0,MACIAS Jose (ARG),MATEUCCI Francisco (URU),WARNKEN Alberto (CHI),201,1090,USA,BEL
2,1930,14 Jul 1930 - 12:45,M,Group 2,Parque Central,Montevideo,Yugoslavia,2,1,Brazil,...,24059,2,0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201,1093,YUG,BRA
3,1930,14 Jul 1930 - 14:50,M,Group 3,Pocitos,Montevideo,Romania,3,1,Peru,...,2549,1,0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201,1098,ROU,PER
4,1930,15 Jul 1930 - 16:00,M,Group 1,Parque Central,Montevideo,Argentina,1,0,France,...,23409,0,0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201,1085,ARG,FRA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279,2019,,F,Quarter-finals,,,Germany,1,2,Sweden,...,,,,,,,,,,
280,2019,,F,Semi-finals,,,England,1,2,United States,...,,,,,,,,,,
281,2019,,F,Semi-finals,,,Netherlands,1,0,Sweden,...,,,,,,,,,,
282,2019,,F,Third place,,,England,1,2,Sweden,...,,,,,,,,,,
283,2019,,F,Final,,,United States,2,0,Netherlands,...,,,,,,,,,,

# Play a game!

In [15]:
men = world_cup_results[world_cup_results['Gender'] == 'M']
women = world_cup_results[world_cup_results['Gender'] == 'F']
# women[women['Home Team Name'] == "Norway"]

#### Maybe this doesn't work because there are not enough matches played

In [16]:
team_1 = input("Team 1")
team_2 = input("Team 2")

Team 1Argentina
Team 2Germany

In [20]:
condition_1 = men['Home Team Name'] == team_1
condition_2 = men['Away Team Name'] == team_2
condition_3 = men['Home Team Name'] == team_2
condition_4 = men['Away Team Name'] == team_1

men[condition_1 & condition_2 | condition_3 & condition_4 ] 
# DATA BASE HAS SOME ERRORS
# 2014 is duplicated and the final we won in Mexico 1986 is not there

,Year,Datetime,Gender,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,...,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
181,1966,16 Jul 1966 - 15:00,M,Group 2,Villa Park,Birmingham,Germany,0,0,Argentina,...,46587,0,0,ZECEVIC Konstantin (YUG),FERNANDES CAMPOS Joaquim (POR),LOEOEW Bertil (SWE),238,1579,FRG,ARG
463,1990,08 Jul 1990 - 20:00,M,Final,Stadio Olimpico,Rome,Germany,1,0,Argentina,...,73603,0,0,CODESAL MENDEZ Edgardo (MEX),PEREZ HOYOS Armando (COL),LISTKIEWICZ Michal (POL),3462,27,FRG,ARG
700,2006,30 Jun 2006 - 17:00,M,Quarter-finals,Olympiastadion,Berlin,Germany,1,1,Argentina,...,72000,0,0,MICHEL Lubos (SVK),Roman SLYSKO (SVK),BALKO Martin (SVK),9.74103e+07,9.74101e+07,GER,ARG
766,2010,03 Jul 2010 - 16:00,M,Quarter-finals,Cape Town Stadium,Cape Town,Argentina,0,4,Germany,...,64100,0,1,Ravshan IRMATOV (UZB),ILYASOV Rafael (UZB),KOCHKAROV Bakhadyr (KGZ),249718,3.00062e+08,ARG,GER
828,2014,13 Jul 2014 - 16:00,M,Final,Estadio do Maracana,Rio De Janeiro,Germany,1,0,Argentina,...,74738,0,0,Nicola RIZZOLI (ITA),Renato FAVERANI (ITA),Andrea STEFANI (ITA),255959,3.00187e+08,GER,ARG
851,2014,13 Jul 2014 - 16:00,M,Final,Estadio do Maracana,Rio De Janeiro,Germany,1,0,Argentina,...,74738,0,0,Nicola RIZZOLI (ITA),Renato FAVERANI (ITA),Andrea STEFANI (ITA),255959,3.00187e+08,GER,ARG

In [18]:
condition_1 = women['Home Team Name'] == team_1
condition_2 = women['Away Team Name'] == team_2
condition_3 = women['Home Team Name'] == team_2
condition_4 = women['Away Team Name'] == team_1

In [19]:
women[condition_1 & condition_2 | condition_3 & condition_4 ]

,Year,Datetime,Gender,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,...,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
101,2003,,F,Group C,,,Argentina,1,6,Germany,...,,,,,,,,,,
116,2007,,F,Group A,,,Germany,11,0,Argentina,...,,,,,,,,,,

## Probability of winning a match

In [ ]:
def probability_of_winning(country, gender_M_or_F):
    
    df = world_cup_results[world_cup_results['Gender'] == gender_M_or_F.upper()]
    
    
    home_team = df[df['Home Team Name'] == country]

    home_loses = len(home_team[(home_team['Home Team Goals']  < home_team['Away Team Goals'])])
    home_wins = len(home_team[(home_team['Home Team Goals']  > home_team['Away Team Goals'])])
    home_draws = len(home_team[(home_team['Home Team Goals']  == home_team['Away Team Goals'])])

    away_team = df[ df['Away Team Name'] == country]
    
    away_loses = len(away_team[(away_team['Home Team Goals']  > away_team['Away Team Goals'])])
    away_wins = len(away_team[(away_team['Home Team Goals']  < away_team['Away Team Goals'])])
    away_draws = len(away_team[(away_team['Home Team Goals']  == away_team['Away Team Goals'])])
    
    loses = home_loses + away_loses
    wins = home_wins + away_wins
    draws = home_draws + away_draws
    total = loses + wins + draws

#     print("loses",home_loses + away_loses)
#     print("Wins",home_wins + away_wins)
#     print("Draws",home_draws + away_draws)
#     print("Total matches played =", total)
    
    if (total == 0):
        return 0
    
    else:
        return wins/total

In [ ]:
probability_of_winning("Argentina", 'f')

In [ ]:
probability_of_winning("Brazil", 'f')

In [ ]:
probability_of_winning("Brazil", 'm')

In [ ]:
probability_of_winning("Sweden", 'm')

In [ ]:
probability_of_winning("Sweden", 'f')

## Add probability of winning to df

In [46]:
world_cup_results.head()

,Year,Datetime,Gender,Stage,Stadium,City,Home Team Name,Home Team Goals,Away Team Goals,Away Team Name,...,Attendance,Half-time Home Goals,Half-time Away Goals,Referee,Assistant 1,Assistant 2,RoundID,MatchID,Home Team Initials,Away Team Initials
0,1930,13 Jul 1930 - 15:00,M,Group 1,Pocitos,Montevideo,France,4,1,Mexico,...,4444,3,0,LOMBARDI Domingo (URU),CRISTOPHE Henry (BEL),REGO Gilberto (BRA),201,1096,FRA,MEX
1,1930,13 Jul 1930 - 15:00,M,Group 4,Parque Central,Montevideo,USA,3,0,Belgium,...,18346,2,0,MACIAS Jose (ARG),MATEUCCI Francisco (URU),WARNKEN Alberto (CHI),201,1090,USA,BEL
2,1930,14 Jul 1930 - 12:45,M,Group 2,Parque Central,Montevideo,Yugoslavia,2,1,Brazil,...,24059,2,0,TEJADA Anibal (URU),VALLARINO Ricardo (URU),BALWAY Thomas (FRA),201,1093,YUG,BRA
3,1930,14 Jul 1930 - 14:50,M,Group 3,Pocitos,Montevideo,Romania,3,1,Peru,...,2549,1,0,WARNKEN Alberto (CHI),LANGENUS Jean (BEL),MATEUCCI Francisco (URU),201,1098,ROU,PER
4,1930,15 Jul 1930 - 16:00,M,Group 1,Parque Central,Montevideo,Argentina,1,0,France,...,23409,0,0,REGO Gilberto (BRA),SAUCEDO Ulises (BOL),RADULESCU Constantin (ROU),201,1085,ARG,FRA

In [47]:
new_men = men.copy()
new_women = women.copy()

new_men['home_team_p'] = new_men['Home Team Name'].apply(lambda x: probability_of_winning( x, 'm'))
new_women['home_team_p'] = new_women['Home Team Name'].apply(lambda x: probability_of_winning( x, 'f'))

In [48]:
world_cup_p = new_men.append(new_women)
world_cup_p = world_cup_p[['Home Team Name','Gender','home_team_p']]
world_cup_p = world_cup_p.groupby(['Home Team Name','Gender']).first()
world_cup_p.reset_index(inplace=True)
world_cup_p.rename(columns={'Home Team Name': 'Country Name_x', 'home_team_p': 'p'}, inplace = True)
world_cup_p.head(15)

   Country Name_x Gender         p
0         Algeria      M  0.214286
1          Angola      M  0.000000
2       Argentina      F  0.000000
3       Argentina      M  0.543210
4       Australia      F  0.269231
5       Australia      M  0.153846
6         Austria      M  0.413793
7         Belgium      M  0.348837
8         Bolivia      M  0.000000
9          Brazil      F  0.588235
10         Brazil      M  0.657407
11       Bulgaria      M  0.115385
12       Cameroon      F  0.375000
13       Cameroon      M  0.173913
14         Canada      F  0.296296

### Clean country names

In [49]:

gender_fifa_df = pd.read_csv('./../../gender-fifa-dataset.csv')
gender_fifa_df.head()

,Country ISO3,Country Name_x,Year,Index,gender_rank,Gender,Country Name_y,fifa_rank,Total Points PTS,Previous Points Prev.Pts,+/-
0,ANG,Angola,2007,0.6034,110.0,F,Angola,105,1181,1181.0,0
1,ANG,Angola,2007,0.6034,110.0,M,Angola,73,443,443.0,0
2,ANG,Angola,2008,0.6032,114.0,F,Angola,94,1184,1184.0,-1
3,ANG,Angola,2008,0.6032,114.0,M,Angola,70,482,476.0,-2
4,ANG,Angola,2009,0.6353,106.0,M,Angola,95,337,337.0,-1

In [50]:
world_cup_p.loc[world_cup_p['Country Name_x'] == 'China PR', 'Country Name_x'] = 'China'
world_cup_p.loc[world_cup_p['Country Name_x'] == "Cï¿½te d'Ivoire", 'Country Name_x'] = "Cote d'Ivoire"
world_cup_p.loc[world_cup_p['Country Name_x'] == 'England', 'Country Name_x'] = 'United Kingdom'
world_cup_p.loc[world_cup_p['Country Name_x'] == 'Korea Republic', 'Country Name_x'] = 'Korea, Rep.'
world_cup_p.loc[world_cup_p['Country Name_x'] == 'Northern Ireland', 'Country Name_x'] = 'Ireland'
world_cup_p.loc[world_cup_p['Country Name_x'] == 'Russia', 'Country Name_x'] = 'Russian Federation'
world_cup_p.loc[world_cup_p['Country Name_x'] == 'Iran', 'Country Name_x'] = 'Iran, Islamic Rep.'
world_cup_p.loc[world_cup_p['Country Name_x'] == 'rn">Bosnia and Herzegovina', 'Country Name_x'] = 'Bosnia and Herzegovina'
world_cup_p.loc[world_cup_p['Country Name_x'] == 'rn">Republic of Ireland'] = 'Ireland'
world_cup_p.loc[world_cup_p['Country Name_x'] == 'rn">Serbia and Montenegro'] = 'Montenegro'
world_cup_p.loc[world_cup_p['Country Name_x'] == 'rn">Trinidad and Tobago'] = 'Trinidad and Tobago'
world_cup_p.loc[world_cup_p['Country Name_x'] == 'rn">United Arab Emirates'] = 'United Arab Emirates'


set_world_cup_p = set(world_cup_p['Country Name_x']) 
set_gender_fifa = set(gender_fifa_df['Country Name_x'])

set_world_cup_p.difference(set_gender_fifa)

{'Chinese Taipei',
 'Czechoslovakia',
 'Equatorial Guinea',
 'Haiti',
 'Ivory Coast',
 'Korea DPR',
 'North Korea',
 'Scotland',
 'Slovakia',
 'South Korea',
 'Soviet Union',
 'USA',
 'Wales',
 'Yugoslavia',
 'Zaire'}

## Save Dataframe

In [51]:
# world_cup_p.to_csv(r'world_cup_probabilities.csv', index = False)